---
extends: default

rules:
  brackets:
    level: warning
    max-spaces-inside: 1
  line-length: disable
  comments:
    require-starting-space: true
    ignore-shebangs: true
    min-spaces-from-content: 1
