---
# This is a composite action that installs npm dependencies or uses cached dependencies
# To improve performance, it uses the cache action to cache the node_modules folder

name: npm-ci
author: "Peter Jokumsen"
description: "Install npm dependencies or use cached dependencies"
branding:
  icon: "arrow-down-circle"
  color: "blue"

inputs:
  working_directory:
    description: "Working directory to use"
    default: "./"
  node_version:
    description: "Node version to use"
    default: "18"
  architecture:
    description: "Architecture to use"
    default: "x64"

runs:
  using: "composite"
  steps:
    - name: Prepare working directory
      id: working_directory
      shell: pwsh
      run: |
        # Add trailing slash to path if not present
        $input = "${{ inputs.working_directory }}"
        if ($input -notlike "*/")
        {
          $input = "${input}/"
        }

        # Check if package-lock.json exists in working directory
        if (Test-Path "${input}package-lock.json")
        {
          Write-Output "package-lock.json found in working_directory '${input}'"
          Write-Output "path=${input}" >> $env:GITHUB_OUTPUT
        }
        else
        {
          Write-Output "::error title='package-lock.json' not found::Could not find package-lock.json in '${input}', adjust working_directory input."
          exit 1
        }

    - uses: actions/setup-node@v3
      name: "Setup Node ${{ inputs.node_version }} w/ Cache"
      id: setup-node
      with:
        node-version: ${{ inputs.node_version }}
        architecture: ${{ inputs.architecture }}
        cache: 'npm'
        cache-dependency-path: ${{ steps.working_directory.outputs.path }}package-lock.json

    - shell: pwsh
      name: Install dependencies
      run: npm ci
