---
# This workflow confirms that the action works on all supported versions of node and OS
# It is not meant to be used by anyone else

name: Test chill-viking/npm-ci

on: # yamllint disable-line rule:truthy
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 5,17 * * *'

permissions:
  contents: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  create-package:
    runs-on: ubuntu-latest
    name: init test package and upload action
    steps:
      - name: Create test package
        run: |
          mkdir testing
          cd testing
          npm init -y
          npm install --save-dev @chill-viking/layout
          rm -rf node_modules

      - name: Upload testing as artifact
        uses: actions/upload-artifact@v3
        with:
          name: test_package
          path: testing

      - name: Checkout latest version of action
        uses: actions/checkout@v3
        with:
          path: npm-ci

      - name: Upload action as artifact
        uses: actions/upload-artifact@v3
        with:
          name: npm-ci
          path: npm-ci

  test-action:
    needs:
      - create-package
    name: test action
    # create a matrix of node versions to test against
    strategy:
      max-parallel: 3
      matrix:
        node-version: [14, 16, 18]
        os: [ubuntu-latest, windows-latest, macos-latest]
        exclude:
          - os: macos-latest
            node-version: 14
          - os: macos-latest
            node-version: 16
          - os: windows-latest
            node-version: 14
          - os: windows-latest
            node-version: 16
    uses: ./.github/workflows/run-action.yml
    with:
      node_major: ${{ matrix.node-version }}
      runs_on: ${{ matrix.os }}
